### ISSUE TITLE
cat copy image

### ISSUE THREAD

**Issue by sevenold** [astrand/xclip#76]
deepin 15.11
xclip 0.12
copy image:
![test](https://user-images.githubusercontent.com/41443157/68994220-6c790b00-08bb-11ea-81e5-751d8c1f875d.png)
copy result:
______________________________________________________________________________
(base) ➜  ~ xclip -selection clipboard -t image/png -o > 1.png
(base) ➜  ~ see 1.png
load translate "/usr/share/dtkwidget/translations/dtkwidget2_zh_CN"
load translate "/usr/share/deepin-image-viewer/translations/deepin-image-viewer_zh_CN"
Setting file: "/home/seven/.config/deepin/deepin-image-viewer/config.conf"
2019-11-16, 21:48:54.195 [Debug  ] [                                                         0] LogFile: "/home/seven/.cache/deepin/deepin-image-viewer/deepin-image-viewer.log"
libpng error: Read Error
libpng error: Read Error
(base) ➜  ~ 
______________________________________________________________________________

**Comment by hackerb9** [comment]
Thank you for the bug report. I believe this was caused by the bug which prevented images larger than 1MB from working. That bug has been fixed and I was able to successfully paste and view the example image you provided.

If you can, please try the version of xclip now available on github and let us know if it is still a problem. If it is, please reopen this bug. Thanks!
